version: '3.8'
services:
  xenforo-vyhub-appealbot:
    container_name: xenforo-vyhub-appealbot
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - VYHUB_API_URL=${VYHUB_API_URL}
      - VYHUB_API_KEY=${VYHUB_API_KEY}
      - XF_URL=${XF_URL}
      - XF_API_KEY=${XF_API_KEY}
      - FORUM_NODE_ID=${FORUM_NODE_ID}
      - FORUM_PREFIX=${FORUM_PREFIX}
    network_mode: 'bridge'
